name: CICD

on:
  pull_request:
    types: [closed]  # Trigger only when a pull request is closed
    branches:
      - master       # Only trigger for pull requests targeting the master branch

jobs:
  build-and-deploy:
    # Run only if the pull request was merged (not closed without merging)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify File Structure
        run: find . -name "user.model.ts"

      - name: Install Dependencies
        run: npm install

      - name: Install Type Definitions (if missing)
        run: npm i --save-dev @types/express @types/jsonwebtoken @types/lodash @types/swagger-ui-express

      - name: Compile TypeScript
        run: npm run build

      - name: Generate Deployment Package
        run: zip -r nodejs-app-build.zip dist package.json package-lock.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'test'
          environment_name: 'Test-env'
          version_label: ${{ github.sha }}
          region: ap-south-1
          deployment_package: nodejs-app-build.zip